Description: Configuration for CANoe participant for SIL Kit Adapter TAP demo
Middleware:
  RegistryUri: silkit://192.168.56.102:8501
# Logging:
  # Sinks:
  # - Type: File
    # Level: Trace
    # LogName: TraceLogFile
